; LAB - 03 (OBJECTIVE 2)
; NAME: BHABESH BEHERA
; REGD NO: 2341002101

;FIND THE GREATEST NUMBER IN ARRAY

PROGRAM:
.DATA
COUNT DB 04H
VALUE DB 09H, 10H, 05H, 03H
RES DB ?
.CODE
MAIN PROC
    MOV AX, DATA
    MOV DS, AX
    MOV CL, COUNT
    DEC CL
    LEA SI, VALUE
    MOV AL, [SI]
    UP: INC SI
    CMP AL, [SI]
    JNL NXT
    MOV AL, [SI]
    NXT: DEC CL
    JNZ UP
    LEA DI, RES
    MOV [DI], AL
    END MAIN